"""Era relacion MnM entre establecimiento y los tipos

Revision ID: 0a4f11f23c9e
Revises: ab2bdc7a7d47
Create Date: 2024-12-10 17:56:52.912012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4f11f23c9e'
down_revision = 'ab2bdc7a7d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establecimiento_tipo_cocina',
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cocina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.ForeignKeyConstraint(['tipo_cocina_id'], ['tipo_cocinas.id'], ),
    sa.PrimaryKeyConstraint('establecimiento_id', 'tipo_cocina_id')
    )
    op.create_table('establecimiento_tipo_servicio',
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicios.id'], ),
    sa.PrimaryKeyConstraint('establecimiento_id', 'tipo_servicio_id')
    )
    op.drop_constraint('tipo_cocinas_establecimiento_id_fkey', 'tipo_cocinas', type_='foreignkey')
    op.drop_column('tipo_cocinas', 'establecimiento_id')
    op.drop_constraint('tipo_servicios_establecimiento_id_fkey', 'tipo_servicios', type_='foreignkey')
    op.drop_column('tipo_servicios', 'establecimiento_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_servicios', sa.Column('establecimiento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tipo_servicios_establecimiento_id_fkey', 'tipo_servicios', 'establecimientos', ['establecimiento_id'], ['id'])
    op.add_column('tipo_cocinas', sa.Column('establecimiento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tipo_cocinas_establecimiento_id_fkey', 'tipo_cocinas', 'establecimientos', ['establecimiento_id'], ['id'])
    op.drop_table('establecimiento_tipo_servicio')
    op.drop_table('establecimiento_tipo_cocina')
    # ### end Alembic commands ###
