"""Eliminar campo contrasena

Revision ID: 62c01ddcc52d
Revises: b305a3cc1308
Create Date: 2025-02-02 15:40:32.992699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c01ddcc52d'
down_revision = 'b305a3cc1308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administradores', 'contrasena_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('administradores', 'contrasena')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administradores', sa.Column('contrasena', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('administradores', 'contrasena_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
