"""Agregar campo contrasena_hash

Revision ID: b305a3cc1308
Revises: dc32a0cd1221
Create Date: 2025-02-02 15:18:36.042485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b305a3cc1308'
down_revision = 'dc32a0cd1221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administradores', sa.Column('contrasena_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administradores', 'contrasena_hash')
    # ### end Alembic commands ###
